#pragma once
#include <locale>	
#include <cwchar>
#include <iostream>
#include <iomanip>
#include <fstream>

#include "Log.h"
#include "In.h"
#include "Parm.h"
#include "Error.h"
#include "LT.h"
#include "IT.h"
#include "tokens-division.h"
#include "PN.h"
#include "MFST.h"
#include "FST.h"
#include "GRB.h"
#include "SemanticAnalys.h"
#include "CodeGenerator.h"
